export  const technologyOptions = [
    "React",
    "TypeScript",
    "JavaScript",
    "Node.js",
    "Express.js",
    "MongoDB",
    "PostgreSQL",
    "MySQL",
    "Tailwind CSS",
    "Next.js",
    "React Native",
    "Redux",
    "Firebase",
    "AWS",
    "Docker",
    "Kubernetes",
    "Jenkins",
    "Github",
    "Python",
    "Django",
    "Flask",
    "Vue.js",
    "Angular",
    "GraphQL",
    "REST API",
    "Microservices",
    "Redis",
    "Elasticsearch",
    "Apache Kafka",
    "Spring Boot",
    "Laravel",
    "PHP",
    "Ruby on Rails",
    "Go",
    "Rust",
    "Java",
    "C#",
    ".NET",
    "Azure",
    "Google Cloud",
    "Terraform",
    "Ansible",
    "Nginx",
    "Apache",
    "Linux",
    "Ubuntu",
    "CentOS",
  ];